// Maps the backend's 4-value AppointmentType enum onto the doctor-facing
// "clinical session type" vocabulary: Initial Consultation, Follow-up,
// Protocol Follow-up, Protocol Device Session. There is no 5th type and no
// separate session table — appointment_type IS the session type.
import type { AppointmentType } from "@/types/domain.types";

export const SESSION_TYPE_LABEL: Record<AppointmentType, string> = {
  initial: "Initial Consultation",
  follow_up: "Follow-up",
  protocol_followup: "Protocol Follow-up",
  device_session: "Device Session",
};

export const SESSION_TYPE_SHORT: Record<AppointmentType, string> = {
  initial: "Initial",
  follow_up: "Follow-up",
  protocol_followup: "Protocol F/U",
  device_session: "Device Session",
};

export const SESSION_TYPE_TONE: Record<AppointmentType, string> = {
  initial: "bg-purple-50 text-purple-700",
  follow_up: "bg-blue-50 text-blue-700",
  protocol_followup: "bg-sky-50 text-sky-700",
  device_session: "bg-orange-50 text-orange-700",
};

/** Manually booked vs. generated by the treatment protocol — the one real
 * difference between Follow-up and Protocol Follow-up (both offer the same
 * clinical actions once opened). */
export function isProtocolGenerated(type: AppointmentType): boolean {
  return type === "device_session" || type === "protocol_followup";
}
