// Maps the backend's 4-value AppointmentType enum onto the doctor-facing
// "clinical session type" vocabulary: Initial Consultation, Follow-up,
// Protocol Follow-up, Protocol Device Session. There is no 5th type and no
// separate session table — appointment_type IS the session type.
import type { Appointment, AppointmentType } from "@/types/domain.types";

export const SESSION_TYPE_LABEL: Record<AppointmentType, string> = {
  initial: "Initial Consultation",
  follow_up: "Follow-up",
  protocol_followup: "Protocol Follow-up",
  device_session: "Device Session",
};

export const SESSION_TYPE_SHORT: Record<AppointmentType, string> = {
  initial: "Initial",
  follow_up: "Follow-up",
  protocol_followup: "Protocol F/U",
  device_session: "Device Session",
};

export const SESSION_TYPE_TONE: Record<AppointmentType, string> = {
  initial: "bg-purple-50 text-purple-700",
  follow_up: "bg-blue-50 text-blue-700",
  protocol_followup: "bg-sky-50 text-sky-700",
  device_session: "bg-orange-50 text-orange-700",
};

/** Manually booked vs. generated by the treatment protocol — the one real
 * difference between Follow-up and Protocol Follow-up (both offer the same
 * clinical actions once opened). */
export function isProtocolGenerated(type: AppointmentType): boolean {
  return type === "device_session" || type === "protocol_followup";
}

/** "tDCS Session" / "tVNS Session" for a single session whose protocol
 * modality is known; falls back to the generic label when modality hasn't
 * loaded yet or the session isn't tied to a protocol. Modality strings
 * (MODALITIES in treatmentProtocol.types.ts) are already the display form. */
export function getDeviceSessionLabel(modality?: string | null): string {
  return modality ? `${modality} Session` : SESSION_TYPE_LABEL.device_session;
}

type ProtocolContext = Pick<
  Appointment,
  "appointment_type" | "device_name" | "condition_names" | "instance_number" | "session_number" | "session_count"
>;

/** Second line for a protocol-born appointment, so a patient running several
 * protocols can tell their sessions apart: "Flow · Depression · Protocol #2 ·
 * Session 5 of 20". Empty for consultations and rows with no protocol data. */
export function protocolContextLine(appt: ProtocolContext): string {
  if (!isProtocolGenerated(appt.appointment_type)) return "";
  const parts: string[] = [];
  if (appt.appointment_type === "device_session" && appt.device_name) parts.push(appt.device_name);
  if (appt.condition_names?.length) parts.push(appt.condition_names.join(", "));
  if (appt.instance_number) parts.push(`Protocol #${appt.instance_number}`);
  if (appt.appointment_type === "device_session" && appt.session_number) {
    parts.push(appt.session_count ? `Session ${appt.session_number} of ${appt.session_count}` : `Session ${appt.session_number}`);
  }
  return parts.join(" · ");
}

/** The doctor to show on an appointment: its own doctor, or — for a device
 * session, which has none — the protocol's prescribing doctor. */
export function appointmentDoctorName(appt: Pick<Appointment, "doctor_name" | "prescribing_doctor_name">): string | null {
  return appt.doctor_name || appt.prescribing_doctor_name || null;
}
