"use client";

/**
 * The clinical assistant's device-session queue.
 *
 * A device session is an appointment with appointment_type='device_session' —
 * there is no separate sessions table (SQL/v1/30 made core.appointments the
 * single row-type for every clinic visit). Each row is generated by a
 * treatment protocol, carries clinic_device_id (which machine it runs on) and
 * NO doctor_id: the CA administers it, so it never occupies a doctor's diary.
 *
 * That is exactly why these rows were invisible until now. They are 'planned'
 * with a date and no start_time, so every calendar view keyed on time slots
 * had nothing to place, and the CA had no route to reach them from.
 */

import { useEffect, useMemo, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import { Activity, Calendar, ChevronRight, Cpu, Loader2, Search, User } from "lucide-react";
import apiClient from "@/lib/api/client";
import { ENDPOINTS } from "@/lib/api/endpoints";
import { useAuth } from "@/lib/hooks";
import { Input, Card, CardContent, PageLoader } from "@/components/ui";

interface SessionRow {
  appointment_id: string;
  appointment_type: string;
  appointment_date: string;
  start_time: string | null;
  end_time: string | null;
  status: string;
  session_number: number | null;
  patient_id: string;
  patient_name: string | null;
  clinic_device_id: string | null;
  protocol_id: string | null;
}

const STATUS_TONE: Record<string, string> = {
  planned: "bg-neutral-100 text-neutral-700",
  selected: "bg-amber-100 text-amber-800",
  paid: "bg-blue-100 text-blue-800",
  checked_in: "bg-indigo-100 text-indigo-800",
  in_progress: "bg-purple-100 text-purple-800",
  completed: "bg-green-100 text-green-800",
  cancelled: "bg-red-100 text-red-700",
  no_show: "bg-red-100 text-red-700",
};

const STATUS_LABEL: Record<string, string> = {
  planned: "Awaiting slot",
  selected: "Slot held",
  paid: "Confirmed",
  checked_in: "Checked in",
  in_progress: "In progress",
  completed: "Completed",
  cancelled: "Cancelled",
  no_show: "No show",
};

function iso(d: Date) {
  return d.toISOString().slice(0, 10);
}

function fmtDate(s: string) {
  return new Date(s + "T00:00:00").toLocaleDateString(undefined, {
    weekday: "short", day: "numeric", month: "short",
  });
}

type RangeKey = "today" | "week" | "all";

export default function ClinicalAssistantAppointmentsPage() {
  const { user } = useAuth();
  const router = useRouter();
  const [rows, setRows]         = useState<SessionRow[]>([]);
  const [loading, setLoading]   = useState(true);
  const [err, setErr]           = useState<string | null>(null);
  const [range, setRange]       = useState<RangeKey>("today");
  const [status, setStatus]     = useState<string>("all");
  const [q, setQ]               = useState("");

  const fetchRows = useCallback(() => {
    setLoading(true);
    setErr(null);

    const today = new Date();
    const params: Record<string, unknown> = {
      // Device sessions only. Without this the CA sees the doctor's
      // consultations too, which are not theirs to run.
      appointment_type: "device_session",
      limit: 200,
    };
    if (range === "today") {
      params.date_from = iso(today);
      params.date_to = iso(today);
    } else if (range === "week") {
      const end = new Date(today);
      end.setDate(end.getDate() + 7);
      params.date_from = iso(today);
      params.date_to = iso(end);
    }

    apiClient
      .get(ENDPOINTS.APPOINTMENTS.LIST, { params })
      .then((res: { data: SessionRow[] }) => setRows(Array.isArray(res.data) ? res.data : []))
      .catch(() => setErr("Couldn't load device sessions."))
      .finally(() => setLoading(false));
  }, [range]);

  useEffect(() => { fetchRows(); }, [fetchRows]);

  const filtered = useMemo(() => {
    const query = q.trim().toLowerCase();
    return rows
      .filter((r) => status === "all" || r.status === status)
      .filter((r) => !query || `${r.patient_name ?? ""} ${r.session_number ?? ""}`.toLowerCase().includes(query));
  }, [rows, status, q]);

  // Grouped by day: a CA works through a date, not a flat list, and these rows
  // carry no time to sort within a day anyway.
  const byDate = useMemo(() => {
    const m = new Map<string, SessionRow[]>();
    for (const r of filtered) {
      const list = m.get(r.appointment_date) ?? [];
      list.push(r);
      m.set(r.appointment_date, list);
    }
    return [...m.entries()].sort(([a], [b]) => a.localeCompare(b));
  }, [filtered]);

  const statuses = useMemo(
    () => ["all", ...Array.from(new Set(rows.map((r) => r.status)))],
    [rows],
  );

  if (loading) return <PageLoader />;

  return (
    <div className="p-6 max-w-6xl mx-auto space-y-5">
      <div>
        <h1 className="text-xl font-bold text-neutral-900">Device Sessions</h1>
        <p className="text-sm text-neutral-500 mt-1">
          Neuromodulation sessions prescribed by a treatment protocol, for {user?.clinic_name ?? "your clinic"}.
        </p>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        {(["today", "week", "all"] as RangeKey[]).map((r) => (
          <button
            key={r}
            onClick={() => setRange(r)}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium transition ${
              range === r ? "bg-neutral-900 text-white" : "bg-neutral-100 text-neutral-700 hover:bg-neutral-200"
            }`}
          >
            {r === "today" ? "Today" : r === "week" ? "Next 7 days" : "All"}
          </button>
        ))}
        <div className="flex-1 min-w-[180px]">
          <div className="relative">
            <Search className="h-4 w-4 text-neutral-400 absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
            <Input
              value={q}
              onChange={(e) => setQ(e.target.value)}
              placeholder="Search patient or session number…"
              className="pl-9"
            />
          </div>
        </div>
      </div>

      <div className="flex flex-wrap gap-1.5">
        {statuses.map((s) => (
          <button
            key={s}
            onClick={() => setStatus(s)}
            className={`px-2.5 py-1 rounded-full text-xs font-semibold transition ${
              status === s ? "bg-neutral-900 text-white" : "bg-neutral-100 text-neutral-600 hover:bg-neutral-200"
            }`}
          >
            {s === "all" ? "All" : STATUS_LABEL[s] ?? s}
          </button>
        ))}
      </div>

      {err && <div className="rounded-lg bg-red-50 text-red-700 text-sm px-3.5 py-2.5">{err}</div>}

      {byDate.length === 0 && !err && (
        <Card>
          <CardContent className="py-12 text-center">
            <Activity className="h-8 w-8 text-neutral-300 mx-auto mb-3" />
            <p className="text-sm font-semibold text-neutral-900">No device sessions</p>
            <p className="text-sm text-neutral-500 mt-1">
              {range === "today"
                ? "Nothing scheduled for today. Try “Next 7 days”."
                : "No sessions match these filters."}
            </p>
          </CardContent>
        </Card>
      )}

      {byDate.map(([date, list]) => (
        <div key={date} className="space-y-2">
          <div className="flex items-center gap-2 text-sm font-semibold text-neutral-700">
            <Calendar className="h-4 w-4 text-neutral-400" />
            {fmtDate(date)}
            <span className="text-neutral-400 font-normal">· {list.length} session{list.length === 1 ? "" : "s"}</span>
          </div>

          <div className="border border-neutral-200 rounded-lg divide-y divide-neutral-100 bg-white">
            {list.map((r) => (
              <button
                key={r.appointment_id}
                onClick={() => router.push(
                  r.status === "in_progress" || r.status === "paused"
                    ? `/clinical-assistant/device-sessions/${r.appointment_id}/live`
                    : r.status === "completed"
                      ? `/clinical-assistant/device-sessions/${r.appointment_id}/summary`
                      : `/clinical-assistant/device-sessions/${r.appointment_id}`
                )}
                className="w-full flex items-center gap-3 px-3.5 py-3 hover:bg-neutral-50 transition text-left"
              >
                <div className="h-9 w-9 rounded-full bg-purple-50 flex items-center justify-center shrink-0">
                  <Cpu className="h-4 w-4 text-purple-600" />
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-semibold text-neutral-900 truncate">
                      {r.patient_name ?? "Unknown patient"}
                    </span>
                    {r.session_number != null && (
                      <span className="text-xs text-neutral-500 shrink-0">Session {r.session_number}</span>
                    )}
                  </div>
                  <div className="flex items-center gap-2 mt-0.5 text-xs text-neutral-500">
                    <User className="h-3 w-3" />
                    {/* 'planned' rows carry a date and no time — the patient
                        picks the slot later. Saying so is more honest than
                        rendering an empty time column. */}
                    <span>{r.start_time ? r.start_time.slice(0, 5) : "No time booked yet"}</span>
                  </div>
                </div>

                <span
                  className={`px-2 py-0.5 rounded-full text-[11px] font-semibold shrink-0 ${
                    STATUS_TONE[r.status] ?? "bg-neutral-100 text-neutral-600"
                  }`}
                >
                  {STATUS_LABEL[r.status] ?? r.status}
                </span>
                <ChevronRight className="h-4 w-4 text-neutral-300 shrink-0" />
              </button>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
